### ISSUE TITLE
Shuffle Cards

### ISSUE THREAD

**Issue by p1839251** [Alone2/studyFlash#1]
Hello,
Is it possible to shuffle cards so I don't practice them in order?

**Comment by Alone2** [comment]
Hey,
It wasn't possible before, but I liked your suggestion and now you can! The [newest](https://github.com/Alone2/studyFlash/releases/tag/v0.6.0) version is now capable of doing this. (It is already in the AUR) 

Here are the [instructions](https://github.com/Alone2/studyFlash/tree/v0.6.0#shuffle-your-cards--)

**Comment by p1839251** [comment]
Thank you for your quick response.
I'm not sure if it's related to this new shuffle option but now I have to answer each questions correctly at least three times.
This may be the intended behavior but earlier versions just exited after a correct answer:
Traceback (most recent call last):
  File "/usr/bin/studyflash", line 120, in <module>
    main()
  File "/usr/bin/studyflash", line 39, in __init__
    if self.testIfArgument(i, arguments[0], y):
  File "/usr/bin/studyflash", line 49, in testIfArgument
    func()
  File "/usr/bin/studyflash", line 75, in study
    study.studyClass(self.path)
  File "/usr/lib/python3.8/site-packages/studyFlash/study.py", line 121, in __init__
    self.evilLoop()
  File "/usr/lib/python3.8/site-packages/studyFlash/study.py", line 160, in evilLoop
    self.evilLoop()
  File "/usr/lib/python3.8/site-packages/studyFlash/study.py", line 160, in evilLoop
    self.evilLoop()
  File "/usr/lib/python3.8/site-packages/studyFlash/study.py", line 160, in evilLoop
    self.evilLoop()
  [Previous line repeated 988 more times]

**Comment by Alone2** [comment]
This is probably a bug I will look into this, and try to fix it as fast as possible. I think if you [reset your statistics](https://github.com/Alone2/studyFlash#reset-your-statistics--) or use an old version it may work again for now.

**Comment by Alone2** [comment]
After looking into it, I think it's intended behavior. (When there's no error message) Before there was an error message when you answered every question correctly. You can stop practicing pressing ctrl+c. The progress will be saved.

If you have a suggestion / questions on how to improve this, just create a new issue.  

What I probably will do, in the next update, is letting the user decide on how many times you have to answer a question correctly for it to not appear anymore.

Thanks for your feedback!

**Comment by p1839251** [comment]
> What I probably will do, in the next update, is letting the user decide on how many times you have to answer a question correctly for it to not appear anymore.

That's exactly what I would have suggested! 
I prefer answering questions once and two more times if I happened to mess them up but I guess this is hard to implement.

**Comment by Alone2** [comment]
It is now possible to decide how many times a question has to be answered correctly for it to not appear anymore. See [here](https://github.com/Alone2/studyFlash#mastered). 

Use  ```studyflash condition FILENAME``` and replace the the last line with something like ```(card.timesCorrect >= 1 and card.timesIncorrect < 1) or card.timesCorrect >= 2``` so you have to answer each question two more times if you get it wrong the first time.

**Comment by p1839251** [comment]
Wow, thank you so much.
However, this specific code `card.timesCorrect >= 1 and card.timesIncorrect < 1` resulted in an infinite loop

**Comment by Alone2** [comment]
Yes ```card.timesCorrect >= 1 and card.timesIncorrect < 1``` results in an infinite loop if you answered the card wrong at least once. 

```card.timesCorrect >= 2``` on the other hand stops a card from appearing when you guessed it correctly more than two times. 

So you can combine the two with "or", which looks something like this: ```(card.timesCorrect >= 1 and card.timesIncorrect < 1) or card.timesCorrect >= 2``` 

So you when you don't answer it correctly the first time, you need to answer it correctly two more times for the card to stop appearing.

**Comment by p1839251** [comment]
Oops, my bad.
I didn't realize it was a single command. I thought they were two approaches.
The 'or' confused me. eh
Thank you for clarifying it.
