### ISSUE TITLE
How to fix typos?

### ISSUE THREAD

**Issue by p1839251** [Alone2/studyFlash#2]
Can I go back to fix typos before hitting the enter key?
Home, End and arrow keys don't work. They just insert characters like ^[[D.
Only backspace seems to work but then it's easier to hit 'c' afterwards.

**Comment by Alone2** [comment]
Using ```studyflash add FILENAME.json```, no you can't. But I suggest you to use ```studyflash edit FILENAME.json ```
It opens your cards in vi, a text editor. Like this you can add/remove cards and even fix typos. 

If you don't know how to use vim or vi (if you're trapped in vi, type ```:wq``` to exit it), you can set the default editor like this: ```studyflash editor FILENAME.json EDITOR```  

If you want an easy editor, I suggest nano: ```studyflash editor FILENAME.json nano```

**Comment by p1839251** [comment]
Sorry for not being clear enough.
I meant if you can fix your mistakes while you're studying:

Here's a 'screenshot'
```
$ studyflash study test 

Question: 1 -> onne
```
This word is actually pretty short so you might only use the backspace key twice to fix it, but is there any way you can remove the extra 'n' without removing the letter 'e'? Arrow keys don't work, as well as HOME or END.
In case you have this [word](https://en.wiktionary.org/wiki/Appendix:List_of_protologisms/Long_words/Titin#Noun) you wouldn't want to start it all over, would you?!

**Comment by Alone2** [comment]
Ah, now I understand what you mean. Yes, you're right, the arrow keys don't work and currently there is no way of removing the 'n' without the 'e' in your example.

 I'll try to fix it :D

**Comment by p1839251** [comment]
Thank you! Keep up the good work!

**Comment by Alone2** [comment]
It is now possible to use the arrow keys. The user interface has completely changed!

The ability to use the END and HOME keys is still bugged in some terminal emulators (#3 )
