### ISSUE TITLE
Import .csv files (semicolon-separated values)

### ISSUE THREAD

**Issue by p1839251** [Alone2/studyFlash#6]
The last thing I'm missing is the ability to import .csv files (technically .ssv but other software refers to them as .csv)

>#CSV EXAMPLE
one;uno
two;dos
three;tres
apple;manzana
pear;pera
peach;melocotón

(Some people may use an 'export to csv' feature too)

**Comment by Alone2** [comment]
Thank you for your suggestion!
I will work on implementing this feature for the next version

**Comment by Alone2** [comment]
You are now able to import / export .csv files like [this](https://github.com/Alone2/studyFlash/blob/master/README.md#importCSV) in the newest version :smile:
