### ISSUE TITLE
About The New UI

### ISSUE THREAD

**Issue by p1839251** [Alone2/studyFlash#7]
Hello,

I was using studyflash and noticed that answers now disappear right after you hitting the enter key.
This makes it impossible to compare what you just typed to the expected answer.

Similarly, both sides of the cards could be visible after giving a right answer, not just a 'correct!' message

**Comment by Alone2** [comment]
Thank you for submitting this issue.
I fixed it now in the newest version.

**Comment by p1839251** [comment]
Thank you for your outstanding work!
I added studyflash to [ArchWiki](https://wiki.archlinux.org/index.php/List_of_applications#Flashcards) because I think it deserves more attention.
I hope you don't mind it.

**Comment by Alone2** [comment]
No, of course I don't mind it. Thank you, I'm glad you like it!
I never expected to see this project on the arch wiki as I just created it for my own use. :smile:
